### ISSUE TITLE
App struggles if PC has multiple IP addresses

### ISSUE THREAD

**Issue by robclark56** [fttx/barcode-to-pc-app#176]
My Desktop has many IP addresses on the one ethernet card.

Auto connection of App -> PC failed. I went through app Select Server settings and saw this:
![image](https://user-images.githubusercontent.com/12369926/78328828-b20c4b00-75b2-11ea-8115-97703a2e1736.png)

I got the connection to work by selecting the IP address that was on the same subnet as the android device.

But each time I restart the app .. it gets confused again and does not connect.

Is this something that can be fixed 
* by me?
* by you?

Thanks

Rob

**Comment by fttx** [comment]
Does it happen even if you close the app first, and then the server?

In theory, it should try to reconnect to the last selected server, but there may be a bug that prevents that when you close the server before closing the app.

You can temporarily fix the issue by blocking the Bonjour Service, so that the server won't communicate the IP addresses. If you use Windows do the opposite of what explained here: https://barcodetopc.com/tutorial/configure-windows-firewall/ only for the Bonjour service part

**Comment by robclark56** [comment]
OK .. got things to behave as follows
* Started server
* started App. Worked fast to answer "No" to the many "...server has changed IP address. Reconnect?" popups (if I didn't work fast .. App would hang.)
* Added a manual server by IP address
* Connected to that one
* Leave server on, and turn close/open App. 
* Indeed .. App was happy as it remembered the last server.

Thanks

Rob

**Comment by fttx** [comment]
I made some changes to improve the server discovery process, can you test it?
Now the server of the other subnets should not appear anymore

[barcode-to-pc-app-v3.9.0-beta2.apk.zip](https://github.com/fttx/barcode-to-pc-app/files/4570308/barcode-to-pc-app-v3.9.0-beta2.apk.zip)

Thank you

**Comment by robclark56** [comment]
Thank you. Much better.

Only one IP address appeared.
