### ISSUE TITLE
Javascript issue

### ISSUE THREAD

**Issue by robclark56** [fttx/barcode-to-pc-app#177]
I am trying to write an output script that removed the 1st 19 characters from a scan.

Here is an example scan:
01993126509999989103070499413080060009928008190912111936

Here is the output I want
03070499413080060009928008190912111936

I have this output template

[JAVSCRIPT FUNCTION = barcode.substring(19)] [ENTER]

But if I select that template and use the App to start a scan with camera, then
* the camera never appears
* a null string gets sent to the server

At one stage I saw the message "Infinite Loop Detected. ..."

What am I doing wrong?

Rob

**Comment by fttx** [comment]
That is because you're missing the [BARCODE] component. This component is responsible for opening the camera and assigning a value to the _barcode_ variable.
Once you put it before the [JAVASCRIPT] component, you have to enable Skip Output, so that it won't interfear

Like this:
![image](https://user-images.githubusercontent.com/5663423/78420162-ecc2c180-764c-11ea-8a9c-af29cd872349.png)

![Uploading image.png…]()

**Comment by fttx** [comment]
https://github.com/fttx/barcode-to-pc-server/issues/247

**Comment by robclark56** [comment]
Excellent.

That worked perfectly.

Love the work you have done. Very intellegent.

Rob
