### ISSUE TITLE
Scan 2 Barcode at same time

### ISSUE THREAD

**Issue by cycleuzbek** [fttx/barcode-to-pc-app#185]
Hello Guys 

We have a questions maybe you may reply us.

1.  May your application scan 2 code bar at same time ? 
2. May your application take a photo and place to session ?

Thank you

**Comment by fttx** [comment]
Hi,

1. If you mean scan two barcodes at the same time by putting them inside the frame at the same time it is not possible.
But what you can do is to create an output template like this:
![image](https://user-images.githubusercontent.com/5663423/80797492-406bf080-8ba2-11ea-8f43-cf54e9aef49d.png)
and keep enabled only one format at the time:
![image](https://user-images.githubusercontent.com/5663423/80797572-76a97000-8ba2-11ea-96ab-741f5c349104.png)
so that it won't get confused when there are two barcodes next to each other

2. Not yet, but since it's a requested feature it may be included in the future versions #129

**Comment by cycleuzbek** [comment]
> 1. If you mean scan two barcodes at the same time by putting them inside the frame at the same time it is not possible.

Why is not possible on same frame ? 

Thank you

**Comment by cycleuzbek** [comment]
> 1. and keep enabled only one format at the time:
>    ![image](https://user-images.githubusercontent.com/5663423/80797572-76a97000-8ba2-11ea-96ab-741f5c349104.png)
>    so that it won't get confused when there are two barcodes next to each other

I already check it and work fine but with iphone ios after scanning 1st barcode camera refresh and take several time how to resolve it ? Use Android LoL ?

Thank you

**Comment by cycleuzbek** [comment]
> 2\. Not yet, but since it's a requested feature it may be included in the future versions #129

Fine

**Comment by cycleuzbek** [comment]
And last question if we have custom project you may support us not for free 👍 

May i have your contact ? or write me in mp

**Comment by cycleuzbek** [comment]
I check Application Scadit may do it.... Why maybe you may integraded for custom work for us ?

Thank you

**Comment by fttx** [comment]
No, I'm sorry at the moment I don't have the resources to do that
