### ISSUE TITLE
"Discard adjacent" option not working when template has 2 barcode components

### ISSUE THREAD

**Issue by eballetbaz** [fttx/barcode-to-pc-app#311]
I have an output template that contains two barcode components in order to collect two barcodes, then the two barcodes are sent using the HTTP component.

When option "Discard adjacent" is enabled, I expect that when scanning the same barcode twice, then the second one is ignored.
This is not the case.
When scanning the barcode twice then each one of the two barcode components contains the same value

Tested with last version: 4.6.2 on Android and IOS

**Comment by fttx** [comment]
I see what the issue is. However, I believe this time it's a specific requirement of yours. To implement what you've described, you can use a custom output template. I've attached an example for your reference.

Please let me know if it works

[Duplicated.btpt.zip](https://github.com/fttx/barcode-to-pc-app/files/13364956/Duplicated.btpt.zip)

**Comment by eballetbaz** [comment]
Many thanks
This is a nice workaround
