### ISSUE TITLE
Android minimum system requirements

### ISSUE THREAD

**Issue by traponto** [fttx/barcode-to-pc-app#85]
What minimum system requirements are required by the application? I tried to install it from Google Play but it tells me that on my device is not possible (Android 4.3, 1.2 GHz Quad Core, 512 MB ram, 4 inches display)

**Comment by fttx** [comment]
API level 19 which corresponds to Android 4.4.
Theoretically, it could work also from API level 16 which is Android 4.1, but i've increased it because a lot of users reported that the app didn't work properly, i guess because of the low amount of ram.

If you want you can decrease that number and recompile the app

1. Install the requirements: https://cordova.apache.org/docs/en/7.x/guide/platforms/android/ (java jdk, android sdk, cordova)
2. Install ionic: https://ionicframework.com/docs/cli/#installation
3. Download the source code: https://github.com/fttx/barcode-to-pc-app/archive/v2.0.0.zip
4. Set minsdkversion to 16:
https://github.com/fttx/barcode-to-pc-app/blob/e6de3681d4f621125c30ed2fc5232f01f2e6f615/config.xml#L18
5. Connect the smartphone to your computer in dev mode, and execute from command line 
```
cd barcode-to-pc-app
npm install
ionic cordova resources
ionic cordova run android
```
